#!/bin/bash
# Nutanix credentials

# PC_IP="{pc-ip}" #(should be in "")
# PORT=9440 #(or any other on which PC is reachable)
# USERNAME="{Username}"
# PASSWORD="{Password}"
# OUTDIR="$(pwd)" #(use $(pwd)/batch-X)
